### ISSUE TITLE
Clear Metrics Description

### ISSUE THREAD

**Issue by 2448845600** [zezhishao/BasicTS#57]
With `CFG.NULL_VAL = 0.0`, three metrics (MAE, RMSE, MAPE) are defaulted as masked ones. Maybe you should use Masked XXX instead of XXX in experimental results?

**Comment by zezhishao** [comment]
Hi thanks for you suggestions.
The “0” is the abnormal value for traffic datasets. Thus, the “MAE” we wanted is indeed the masked ones, since calculating errors on abnormal values and forcing models to fit these abnormal data does not make any sense. Almost all the previous works followed this setting and reported these metrics without the “mask”.
Moreover, the default null values of these metrics is nan, instead of 0.0, since in many dataset's the “0” is not abnormal values.

**Comment by 2448845600** [comment]
Thanks!
